### ISSUE TITLE
Ask for Help(about the results)

### ISSUE THREAD

**Issue by THSWind** [KarlXing/RLCodebase#8]
Could you tell me how to compare this results with another  algorithm(don't in your repo) results.
your results is a form of episodic return, another repo's results is ..

by the way,  in your repo, every algo. use env=16. I don't know if this will influence the result at the same total timesteps. (if 100 steps here the same as 10000 steps other normal algo.( unspeed algo.))

I wish you can know what I mean, waiting for your reply~ thanks a lot

**Comment by KarlXing** [comment]
Hi, it looks like another repo's results is missing in your description. I think episodic return is a common measurement for comparison. One way to compare results is plotting them in one figure. You can also use np.interp to fit the results to the same x ticks before that. 

I guess your question is related to the way that this repo does the log. All the log in this repo are based on the global/total time steps. For example, we could run 10 environments at the same time. Running the algorithm for 10 steps means the total time steps is already 100. Let's say we run one more step and find the second environment ends with episodic return of 500. Then we will log the data as (102, 500) where 102 is the global time step and 500 is the episodic return.

I hope it answers your questions. Let me know if you still have questions.

**Comment by THSWind** [comment]
Thank you, I'm appreciate it~

**Comment by THSWind** [comment]
Hello, KarlXing,

My works has take average reward as a measurement for comparison. Now, I need run a2c(or ddpg) with the same measurement(average reward). do you know where have it? or give me some advice? It puzzled me many days

ps: a2c, ddpg   atari

**Comment by KarlXing** [comment]
So you need average rewards per step right? Since we have the episodic rewards, the only thing we need is the episodic length. Luckily, we do have that information although I didn't include it in the log (see https://github.com/KarlXing/RLCodebase/blob/master/rlcodebase/env/envs.py#L177). You could refer the way that I save episodic returns to save the episodic length too. 

Another choice is calculating the episodic length from the log we have. You could get all episodic rewards of _ith_ environment by finding logs whose global_step satisfying `global_step % num_environments == i`. Then you could also easily get episodic length and calculate average rewards per step.

**Comment by THSWind** [comment]
thanks for your patience~
you have inspired me, I plan to use openai/baselines, and do something as you say~
